# Generated by Django 4.2.7 on 2025-08-15 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('grower', 'Inspección del productor'), ('quality', 'Inspección de calidad'), ('phytosanitary', 'Inspección fitosanitaria')], max_length=20, verbose_name='Tipo de inspección')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('inspection_point', models.CharField(max_length=100, verbose_name='Punto de inspección')),
                ('inspector', models.CharField(max_length=100, verbose_name='Inspector')),
                ('inspection_date', models.DateTimeField(verbose_name='Fecha de inspección')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('variety', models.CharField(blank=True, max_length=50, verbose_name='Variedad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Referencia')),
                ('shipper', models.CharField(max_length=100, verbose_name='Expedidor')),
                ('consignee', models.CharField(max_length=100, verbose_name='Consignatario')),
                ('transport_type', models.CharField(choices=[('road', 'Transporte terrestre'), ('sea', 'Transporte marítimo'), ('air', 'Transporte aéreo')], max_length=20, verbose_name='Tipo de transporte')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, verbose_name='ID de muestra')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unidad')),
                ('location_taken', models.CharField(max_length=100, verbose_name='Ubicación de toma')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='production.inspection', verbose_name='Inspección')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['sample_id'],
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nivel de pH')),
                ('defects_found', models.TextField(blank=True, verbose_name='Defectos encontrados')),
                ('overall_quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Mala')], max_length=20, verbose_name='Calidad general')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='production.inspection', verbose_name='Inspección')),
            ],
            options={
                'verbose_name': 'Reporte de Calidad',
                'verbose_name_plural': 'Reportes de Calidad',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.shipment', verbose_name='Embarque'),
        ),
    ]
