# Generated by Django 4.2.7 on 2025-08-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_add_profile_image_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH')),
                ('firmeza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Firmeza')),
                ('solidos_solubles', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sólidos Solubles (°Brix)')),
                ('acidez_titulable', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Acidez Titulable (%)')),
                ('defectos_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Defectos')),
                ('defectos_descripcion', models.TextField(blank=True, verbose_name='Descripción de Defectos')),
                ('calibre', models.CharField(blank=True, max_length=50, verbose_name='Calibre')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('calidad_general', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=20, verbose_name='Calidad General')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('processed_data', models.JSONField(default=dict, verbose_name='Datos Procesados de la API')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_data', to='authentication.company', verbose_name='Empresa del Sistema')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Dato de Calidad',
                'verbose_name_plural': 'Datos de Calidad',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['empresa'], name='quality_dat_empresa_b67442_idx'), models.Index(fields=['fecha_registro'], name='quality_dat_fecha_r_e0be36_idx'), models.Index(fields=['calidad_general'], name='quality_dat_calidad_ccd0ec_idx'), models.Index(fields=['aprobado'], name='quality_dat_aprobad_178e15_idx')],
            },
        ),
    ]
