# Generated by Django 4.2.7 on 2025-08-15 07:52

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='Dominio')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='Logo (Base64)')),
                ('rubro', models.CharField(choices=[('agricultura', 'Agricultura'), ('fruticultura', 'Fruticultura'), ('horticultura', 'Horticultura'), ('viticultura', 'Viticultura'), ('ganaderia', 'Ganadería'), ('avicultura', 'Avicultura'), ('porcicultura', 'Porcicultura'), ('acuicultura', 'Acuicultura'), ('apicultura', 'Apicultura'), ('otros', 'Otros')], max_length=50, verbose_name='Rubro')),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('PE', 'Perú'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('MX', 'México'), ('US', 'Estados Unidos'), ('CA', 'Canadá'), ('ES', 'España'), ('FR', 'Francia'), ('DE', 'Alemania'), ('IT', 'Italia'), ('NL', 'Países Bajos'), ('GB', 'Reino Unido'), ('AU', 'Australia'), ('NZ', 'Nueva Zelanda'), ('CN', 'China'), ('JP', 'Japón'), ('KR', 'Corea del Sur'), ('IN', 'India'), ('ZA', 'Sudáfrica'), ('OT', 'Otros')], max_length=2, verbose_name='País')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'auth_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('operator', 'Operador'), ('viewer', 'Visualizador')], max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permisos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'auth_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_client', models.BooleanField(default=True)),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.role', verbose_name='Rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
