# Generated by Django 4.2.7 on 2025-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Imagen de perfil en Base64', null=True),
        ),
    ]
